### ISSUE TITLE
Release for specs2 3.1

### ISSUE THREAD

**Issue by julien-truffaut** [typelevel/scalaz-specs2#16]
Would it be possible to get a release for the latest version of specs2?

**Comment by julien-truffaut** [comment]
can we also bump scalacheck? I think the latest version is 1.12.2

**Comment by larsrh** [comment]
Yes, will do, probably on Saturday.

**Comment by julien-truffaut** [comment]
Thank you @larsrh

**Comment by larsrh** [comment]
Just uploaded 0.4.0 to Sonatype.

**Comment by julien-truffaut** [comment]
@larsrh could you cross build it? 0.4.0 doesn't exist for scala 2.10

**Comment by larsrh** [comment]
I just realised that I bumped to specs2 3.2, which apparently doesn't exist for 2.10. /cc @etorreborre

**Comment by etorreborre** [comment]
[Done](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.10/3.2). Sorry about that.

**Comment by julien-truffaut** [comment]
@larsrh would you mind to release a version for 2.10?

**Comment by larsrh** [comment]
Sure thing, will do.

**Comment by julien-truffaut** [comment]
awesome, thanks

**Comment by larsrh** [comment]
Done
