### ISSUE TITLE
Release new version for scalaz 7.2.x

### ISSUE THREAD

**Issue by jedesah** [typelevel/scalaz-specs2#23]

**Comment by larsrh** [comment]
I'm still seeing eviction warnings:

```scala
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.scalaz:scalaz-core_2.11:(7.1.4, 7.2.0) -> 7.2.1 (caller: org.typelevel:scalaz-specs2_2.11:0.5.0-SNAPSHOT, org.scalaz.stream:scalaz-stream_2.11:0.8 (), org.scalaz:scalaz-effect_2.11:7.2.0, org.scalaz:scalaz-concurrent_2.11:7.2.0, org.specs2:specs2-common_2.11:3.7)
[warn]  * org.scalaz:scalaz-concurrent_2.11:7.1.4 -> 7.2.0 (caller: org.scalaz.stream:scalaz-stream_2.11:0.8 (), org.specs2:specs2-common_2.11:3.7)
```

I'm not quite sure where they're coming from.

**Comment by jedesah** [comment]
The version of `scalaz-stream` is wrong, it should be `0.8a`.

**Comment by larsrh** [comment]
But there's no mention of `scalaz-stream` here. Is this a problem in specs2?

**Comment by jedesah** [comment]
Ya, I was going to say. Seems like it might be a mistake on the part of `specs2` because it might be both using scalaz `7.2` and scalaz-stream `0.8` which would be incorrect.

**Comment by larsrh** [comment]
Paging @etorreborre.

**Comment by jedesah** [comment]
Here we go: https://github.com/etorreborre/specs2/commit/ed093a4b907e607808347e49936453dbc500c6a7

Looks like that puts us between a rock and a hard place because `3.7` is last version that builds on scalacheck 1.12.5 and yet it's got this problem with scalaz.

**Comment by larsrh** [comment]
I can certainly release with broken dependencies, but is it a good idea?

**Comment by larsrh** [comment]
That came out harsher than I wanted … I mean, obviously specs2 works in that version. So it's probably more of a cosmetic matter.

**Comment by jedesah** [comment]
Ya, it seems to be kind of a `specs2` issue for that particular version. Too bad we can't just update to the latest because of `scalaz`.

**Comment by etorreborre** [comment]
@larsrh @jedesah I am trying to understand which versions are being required here:

 - scalaz 7.2
 - scalaz-stream 0.8a
 - scalacheck 0.12.5

I can release a version of specs2 called `3.7.3-scalacheck-0.12`. It would actually be nice to have version of `scalaz-scalacheck-binding` using scalacheck  0.13 because the lack of upgrade also caused me issues in the past. And then it would be possible to use a recent specs2 version.

**Comment by jedesah** [comment]
@etorreborre If my analysis is correct, version `3.7` of `specs2` was published against `scalaz` `7.2` and `scalaz-stream` `0.8` which leads to eviction warnings for downstream projects because `0.8` uses `scalaz` `7.2` as opposed to `0.8a` which uses `scalaz` `7.1.x` (pretty sure you are aware of that now, because of the change you made in a subsequent version)

`3.7.3-scalacheck-0.12` would certainly fix this problem. I don't know how easy it would be to get a new version of `scalaz-scalacheck-binding` published against `scalacheck` `0.13.0`

**Comment by etorreborre** [comment]
I'll try to find some time to do that later on today.

**Comment by larsrh** [comment]
> I don't know how easy it would be to get a new version of scalaz-scalacheck-binding published against scalacheck 0.13.0

That's a question for @xuwei-k.

**Comment by etorreborre** [comment]
@jedesah please check if [this one](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.7.3-scalacheck-1.12/) works for you.

**Comment by larsrh** [comment]
@jedesah If you could PR this it'd be great.

**Comment by malcolmgreaves** [comment]
Hello! This is a critical problem for me right now: I am trying to use specs2 with scalaz 7.2.x. Is there a schedule for releasing a fix?

**Comment by etorreborre** [comment]
@malcolmgreaves can you list all the dependencies you need? Would [specs2-3.7.3-scalacheck-1.12](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-common_2.11/3.7.3-scalacheck-1.12/specs2-common_2.11-3.7.3-scalacheck-1.12.pom) be ok for you?

**Comment by malcolmgreaves** [comment]
Hi @etorreborre ! This helped me out a ton! I was able to resolve my problem. I tried both your specific suggestion as well as using version `3.8.5` in my use case. I ended up going with thee following dependencies:

    val ver                  = "3.8.5"
    val specs2Core  = "org.specs2" %% "specs2-core"                   % ver
    val specs2Mock = "org.specs2" %% "specs2-mock"                 % ver
    val specs2Extra  = "org.specs2" %% "specs2-matcher-extra" % ver


Thank you very much!

**Comment by larsrh** [comment]
Just to clarify: Is there anything needed from my end? I don't follow the development of specs2/scalaz closely, so any hints on concrete changes would be greatly appreciated.

**Comment by larsrh** [comment]
`v0.5.0` out now.
